steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'devops-app'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _REGION: 'us-central1'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app:$SHORT_SHA'
