steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'devops-app',
        '--image',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/devops-repo/devops-app'

